spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**

        - id: theatre-service
          uri: lb://theatre-service
          predicates:
            - Path=/theatres/**

        - id: show-service
          uri: lb://show-service
          predicates:
            - Path=/shows/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080